### PR TITLE
Pull request for moverscore_v2 GPU modification

### PR DESCRIPTION
**Pull request by jabirshabbir**

### CODE REVIEW

**Comment by forrestbao** [comment]
This PR will allow moverscore_v2.py to run with GPU support.

**Review by vejvarm — CHANGES_REQUESTED** [review]
It's good, I'd just suggest 2 small tidbit changes.

1. add a failsafe if only CPU is available, like this:
`device = 'cuda' if torch.cuda.is_available() else 'cpu'`

2. any point where you use `device='cuda:0'` can be changed to `device=device` to unify everything under one variable.

Otherwise it's working like a charm for me :) Good job!

**Comment by andyweizhao** [comment]
Thank you so much!

**Comment by forrestbao** [comment]
We noticed something very interesting that even after this PR, the GPU utility rate is still very low. One CPU core is occupied most of the time while the GPU is almost idle. We think the reason is on the implementation of tokenization, padding, etc. 

https://github.com/AIPHES/emnlp19-moverscore/blob/0459a3b3b3bd73baa0cc515a355228ee5a2887e0/moverscore_v2.py#L78-L86

**Comment by andyweizhao** [comment]
Inefficient use of GPU is because the current WMD algorithm computes one instance at a time, even though inputs are given in the batch format. So GPU remains idle until WMD finishes a batch of computation instance by instance.

**Pull request merged**
